### ISSUE TITLE
Kraken Public Spot Rest API Client

### ISSUE THREAD

**Issue by rewong03** [northwesternfintech/desk-monorepo#27]
https://docs.kraken.com/api/docs/category/rest-api/market-data/

Wrapper for ^ with the support for the following routes:
- https://docs.kraken.com/api/docs/rest-api/get-system-status
- https://docs.kraken.com/api/docs/rest-api/get-asset-info
- https://docs.kraken.com/api/docs/rest-api/get-tradable-asset-pairs
  - for only the assets in the types enum
- https://docs.kraken.com/api/docs/rest-api/get-ohlc-data
- https://docs.kraken.com/api/docs/rest-api/get-order-book
- https://docs.kraken.com/api/docs/rest-api/get-recent-trades
- https://docs.kraken.com/api/docs/rest-api/get-recent-spreads

**Comment by echavemann** [comment]
this is just public right

**Comment by rewong03** [comment]
yeah

**Comment by rewong03** [comment]
let's make the following?
- adapters/kraken/spot/containers.py
- adapters/kraken/spot/kraken_spot_client.py
