### ISSUE TITLE
Kraken Public Futures API Client

### ISSUE THREAD

**Issue by rewong03** [northwesternfintech/desk-monorepo#28]
https://docs.kraken.com/api/docs/futures-api/trading/get-history

Wrapper for ^ with support for the following routes:
- https://docs.kraken.com/api/docs/futures-api/trading/get-history
- https://docs.kraken.com/api/docs/futures-api/trading/get-orderbook

**Comment by rewong03** [comment]
@echavemann add whatever other routes u want

**Comment by kyeoul** [comment]
These are supposed to be wrapper methods for KrakenFutureClient right

**Comment by rewong03** [comment]
yeah
