### ISSUE TITLE
Migrate Record-like classes to Attrs

### ISSUE THREAD

**Issue by egelja** [northwesternfintech/desk-monorepo#33]
This kind of class is bugprone (several things to change on update), and doesn't have good DX (no overloaded `__repr__`, for example)

https://github.com/northwesternfintech/desk-monorepo/blob/34a1645788280735cb0aad8c377d565412082a68/src/pysrc/adapters/messages.py#L34-L51

[`attrs`](https://www.attrs.org/en/stable/) does all these things for you automagically, *with type safety*, and it would be good to update these kinds of classes to use it.

**Comment by echavemann** [comment]
no magic

**Comment by echavemann** [comment]
go do your nuftsite backlog smh
