### ISSUE TITLE
Data Ingest: Preprocessing

### ISSUE THREAD

**Issue by echavemann** [northwesternfintech/desk-monorepo#45]
Currently for Binance data, we spend 1200 bucks on the data from tardis.dev. The data is kind of trash but its by far the cheapest option. Kraken offers free historical downloads: https://support.kraken.com/hc/en-us/articles/360047543791-Downloadable-historical-market-data-time-and-sales-

We want to download these, and then we want to parse them into a useable format. In walkway we use `msgpack` and `lz4`, but I think it is fine if we just cut up the csvs into daily chunks and then compress them with whatever compression library. Maybe ztd? https://github.com/facebook/zstd

We should add a very small integration test for this, but just keep the file size low so the test can run quickly.

**Comment by rewong03** [comment]
so sounds like we want two separate things?
1. code to download the zip from the google drive in that kraken link, chunk it into daily csvs, compress and save locally
2. code to decompress the csvs from local and parse into data structure

**Comment by echavemann** [comment]
yup. CSVs are also a bad format, feel free to tweak to do something faster

**Comment by rewong03** [comment]
#52
