### ISSUE TITLE
C++ Tooling

### ISSUE THREAD

**Issue by echavemann** [northwesternfintech/desk-monorepo#47]
Prereq for backtester (Steve)

**Comment by stevenewald** [comment]
U want me to make another repo for cpp? @echavemann

**Comment by echavemann** [comment]
No, you'll need to add cpp tooling to this one... otherwise how is it a mono repo lol

**Comment by stevenewald** [comment]
Mb meant another project within the repo, not another repo

**Comment by stevenewald** [comment]
Tbh looking at the repo rn im not sure you set it up correctly **to be** a monorepo. Why is there one src?

**Comment by echavemann** [comment]
confusion is resolved in slack yea?

**Comment by echavemann** [comment]
Taking this over because it is taking forever...

**Comment by echavemann** [comment]
ez
